Revert "[package_index_cros] Fix compiler argument fix."
This reverts commit 3e83dfa7d857ea040bbe42d67dc099672047a440.

Reason for revert: AttributeError: 'CrosSdk' object has no attribute 'Which'

Original change's description:
> [package_index_cros] Fix compiler argument fix.
>
> Fix iteration over arguments and do not fix the 1st compiler argument
> twice.
>
> Add clang options to skip. Add more sophisticated fixing of the compiler
> (taken from crrev.com/c/3850103).
>
> Change-Id: I41b85db74aaa5ba1a44c8aa0aea87a798d932ed7
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/3878352
> Reviewed-by: Gavin Mak <gavinmak@google.com>
> Commit-Queue: Artem Sumaneev <asumaneev@google.com>
> Cr-Commit-Position: refs/heads/main@{#51413}

Change-Id: I5239552e02b1114620bbdb6f93ef9283bfada7b0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/3885455
Auto-Submit: Gavin Mak <gavinmak@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#51420}