siso: add file semaphore in reapi cas
When too many missing inputs in RBE-CAS, reapi will try
to read contents to construct BatchUpdateBlobs.
Without limit, it would cause lots of thread and may end
with runtime faiure
 runtime: program exceeds 10000-thread limit
 fatal error: thread exhaustion

Add semaphore to limit lots of concurrent file read.

Change-Id: I531227116236a798424560135a9e8132b991906a
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5411513
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#64196}