Close fd before trying to rename the file.
This is an attempt to fix failures on Windows such as:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\b\\s\\w\\ir\\x\\w\\recipe_cleanup\\.dockerbuildai4z1idk\\temp\\psutil-5.9.8rr0m7dkk\\download\\file' -> 'C:\\b\\s\\w\\ir\\x\\w\\recipe_cleanup\\.dockerbuildai4z1idk\\temp\\psutil-5.9.8rr0m7dkk\\package\\psutil-5.9.8.tar.gz'

( https://ci.chromium.org/ui/p/infra-internal/builders/try/Windows-x86%20wheel%20builder/b8748708472228490257/overview )

Change-Id: I2595e8179f97ff1f48bedd68f4aa5e51352e6b9c
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5514893
Reviewed-by: Chenlin Fan <fancl@chromium.org>
Commit-Queue: Chenlin Fan <fancl@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Auto-Submit: Brian Ryner <bryner@google.com>
Cr-Commit-Position: refs/heads/main@{#65158}