Reland "siso: drop gn.parse_args"
This reverts commit 9b0c775d20ae645605d23eccd10cedda4b4e2700.

Reason for revert: day passed
*-build-perf-developer builders are already building after gn.parse_args -> gn.args fix.


Original change's description:
> Revert "siso: drop gn.parse_args"
>
> This reverts commit 4269933b3b0474994d667a36d2cd0ef5f9807e38.
>
> Reason for revert:
> https://ci.chromium.org/ui/p/chromium/builders/ci/win-build-perf-developer/1765/overview
>
> error: failed to run init: module has no .parse_args field or method
>
> need to wait for a day?
>
> Original change's description:
> > siso: drop gn.parse_args
> >
> > gn.parse_args can't handle import.
> > Already use gn.args(ctx) in chromium build/config/siso by
> > https://chromium-review.googlesource.com/c/chromium/src/+/4924713
> >
> > Bug: b/303338337
> > Change-Id: Ib08501569baeb6547fb29f912c2ff74ddcb7c9f3
> > Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4930348
> > Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> > Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#60318}
>
> Bug: b/303338337
> Change-Id: Idfd8561ada73e5b8f8e6cf9411f657cac0c91ee8
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4930748
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> Cr-Commit-Position: refs/heads/main@{#60321}

Bug: b/303338337
Change-Id: If2198000ff3733a6a97d9224a64e1957162a3cec
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4931129
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#60351}