Revert "UFS, skylab, shivas: Add new label trrs_type"
This reverts commit 515aee0a95e2ee7d0c06511ef5a590fdf4b39550.

Reason for revert: 
tree closed by 
https://ci.chromium.org/p/infra/builders/ci/infra-continuous-bionic-64/23598?

=== RUN   TestChameleonCleanAndValidateFlags
    chameleon_test.go:88: cleanAndValidateFlags = "Wrong usage!!\nInvalid TRRS type specified (ABCD), only supports (CTIA,OMTP)"; want err "Invalid TRRS type specified (ABCD), only supports (OMTP,CTIA)" included
--- FAIL: TestChameleonCleanAndValidateFlags (0.00s)

Original change's description:
> UFS, skylab, shivas: Add new label trrs_type
>
> Added new label trrs_type enum to chameleon proto in UFS and Skylab.
>
> Added new flag trrs to chameleon peripheral.
>
> This is needed to differentiate between OMTP and CTIA standard for static analog audio tests.
>
> BUG=b:293983039
> TEST=cd ~/cr/infra/go/src/infra/libs/skylab && go generate ./... && go test ./...
> TEST=cd ~/cr/infra/go/src/infra/unifiedfleet && make gen && make build && make test
> TEST=cd ~/cr/infra/go/src/infra/cmd/shivas && make test
>
> Change-Id: Ia09da10e3be8c1fd10444416b13e324fef81d038
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4728814
> Reviewed-by: YJ Lee <yunjunlee@chromium.org>
> Commit-Queue: Eugene Low <elow@google.com>
> Reviewed-by: Yang Yang <echoyang@chromium.org>
> Reviewed-by: Garry Wang <xianuowang@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#58699}

BUG=b:293983039
No-Presubmit: true
No-Tree-Checks: true
No-Try: true

Change-Id: I1f08fb5ea58651f65c1568fe872f322c0760e04b
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4751619
Reviewed-by: YJ Lee <yunjunlee@chromium.org>
Reviewed-by: Eugene Low <elow@google.com>
Reviewed-by: Garry Wang <xianuowang@chromium.org>
Reviewed-by: Yang Yang <echoyang@chromium.org>
Commit-Queue: Yang Yang <echoyang@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#58703}