Revert "Reland Revert "🚝 Add dependencies for google-cloud-tasks""
This reverts commit 69ffbe84bcfd62790aaedf4130f8ac93cb4e739d.

Reason for revert: Fails in deployed env:
File "/base/data/home/apps/s~monorail-dev/monorail-dev-default-v074.429528265599786424/appengine_config.py", line 22, in <module>
    vendor.add(lib_path)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/d0142b475980dc59/python27/python27_lib/versions/1/google/appengine/ext/vendor/__init__.py", line 44, in add
    'No such virtualenv or site directory' % path)
ValueError: virtualenv: cannot access /base/data/home/apps/s~monorail-dev/monorail-dev-default-v074.429528265599786424/lib: No such virtualenv or site directory

Original change's description:
> Reland Revert "🚝 Add dependencies for google-cloud-tasks"
> 
> This reverts commit 9d2e063e02f676e2b081d94584d35bf3f86812bd.
> 
> Bug: monorail:8169
> Change-Id: I6c61e7813c78346ce75bcb2d800373b3ce36b5c4
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2402120
> Reviewed-by: Dave Tu <dtu@chromium.org>
> Commit-Queue: Kevin Weng <kweng@google.com>
> Cr-Commit-Position: refs/heads/master@{#34966}

TBR=dtu@chromium.org,kweng@google.com,infra-scoped@luci-project-accounts.iam.gserviceaccount.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: monorail:8169
Change-Id: Id094b76075af2deff9c7d1b0210899d456507ecb