Update all Go GAE second gen apps to go116 runtime.
Dependencies of infra Go code require go116 now. In particular
golang.org/x/net does, manifesting as following error when trying
to deploy to <go116:

   .../http2/transport.go:416:45: undefined: os.ErrDeadlineExceeded

It should be safe, there are no big changes between >=go113
and go116 runtimes.

R=iannucci@chromium.org, tikuta@chromium.org

Change-Id: I8e7dca8a88507d4a9a261a5f549968ee7e09caa2
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/3661636
Reviewed-by: Xixuan Wu <xixuan@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Cr-Commit-Position: refs/heads/main@{#49260}