siso: fix directory store race
without fix of this CL, TestStat_Race flaky fails

$ go test -count 100 ./hashfs
...
--- FAIL: TestStat_Race (0.03s)
    fs_test.go:281: hashFS.Stat(ctx, "/tmp/TestStat_Race1094022953/001",
    "third_party/breakpad/breakpad/src/google_breakpad/common/minidump_format.h"):
    store race minidump_format.h: 0xc00051a0e0 -> 0xc00040a460 ->
    0xc0004be0e0 true; want nil

It will use the previous *entry if new entry has zero digest.
it would be previous *entry has been calculated digest and has non zero
digest. it would happen by concurrent Stat etc, which is
likely happens with scandeps.

If new entry has non-zero digest (i.e. Update by command outputs),
digest should match to use the previous *entry.

Bug: b/282888305
Change-Id: I72fa6ac88e816c348045816bde92b8bf6023a544
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4560535
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#56976}