Revert "cros-publish: refactor test runs population"
This reverts commit 6d708e3d03428c832c6e3530d6c556db5f3301a0.

Reason for revert: 
https://ci.chromium.org/ui/p/infra/builders/ci/infra-continuous-jammy-64/8252/overview

=== RUN   TestRdbPublishPublishCmd_ExtractDepsSuccess
=== PAUSE TestRdbPublishPublishCmd_ExtractDepsSuccess
=== CONT  TestRdbPublishPublishCmd_ExtractDepsSuccess
--- FAIL: TestRdbPublishPublishCmd_ExtractDepsSuccess (0.02s)

Original change's description:
> cros-publish: refactor test runs population
>
> Create modular functions to populate test runs.
>
> Bug: b:335910070
> Test: unit test
> Change-Id: I70f86829f02278423470f089abee183ad513a1e2
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5481378
> Reviewed-by: Jason Kusuma <jkusuma@google.com>
> Commit-Queue: Zhihui Xie <zhihuixie@google.com>
> Cr-Commit-Position: refs/heads/main@{#64827}

Bug: b:335910070
Change-Id: I4b008da8189caa605821a17e4df1c8a608fa8083
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5493539
Reviewed-by: Junji Watanabe <jwata@google.com>
Commit-Queue: Junji Watanabe <jwata@google.com>
Reviewed-by: Zhihui Xie <zhihuixie@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#64829}