[docker] Allow downgrading packages
The error noticed on build456-a9.labs when bringing up the docker
instances indicates the downgrading should be allowed.

```
E: Packages were downgraded and -y was used without --allow-downgrades.
Unable to install/upgrade docker-ce to docker-ce=5:19.03.8~3-0~ubuntu-bionic.
Traceback (most recent call last):
  File "/opt/swarm-docker/infra/services/swarm_docker/main_helpers.py", line 106, in update_docker
    subprocess.check_call(['/usr/bin/apt-get', 'install', '-y',
  File "/opt/vpython/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/apt-get', 'install', '-y', 'docker-ce=5:19.03.8~3-0~ubuntu-bionic']' returned non-zero exit status 100.
```

Change-Id: I6075f3e9094097cb9de708f82b54b0ff7fb08683