env.cmd: Use vpython3 instead of vpython to fix crash.
Before:

google\philwo@PHILWIN C:\src\chrome_infra\infra\go\src\infra\build\siso>call ..\..\..\..\env.cmd
INFO:bootstrap:Infra version is out of date.
INFO:bootstrap:Installing Go toolset.
INFO:bootstrap:  Old toolset is None
INFO:bootstrap:  New toolset is 1.21.0.chromium1
Traceback (most recent call last):
  File "C:\src\chrome_infra\infra\go\\env.py", line 126, in <module>
    main()
  File "C:\src\chrome_infra\infra\go\\env.py", line 81, in main
    new = bootstrap.prepare_go_environ()
  File "C:\src\chrome_infra\infra\go\bootstrap.py", line 577, in prepare_go_environ
    bootstrap(LAYOUT, logging.INFO)
  File "C:\src\chrome_infra\infra\go\bootstrap.py", line 539, in bootstrap
    layout.toolset_root, toolset_version)
  File "C:\src\chrome_infra\infra\go\bootstrap.py", line 297, in ensure_toolset_installed
    remove_file([toolset_root, 'INSTALLED_TOOLSET'])
  File "C:\src\chrome_infra\infra\go\bootstrap.py", line 147, in remove_file
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

After:

Works fine.

Change-Id: I6cc5ae0d23eeccbef7c4d87b1011016858af6075
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4853471
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Philipp Wollermann <philwo@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#59618}