Revert "Revert "android-docker: Wrap container logic in a flock.""
This reverts commit 9c5733577ab8a95234bab00982a91da93c818d1e.

Reason for revert: path errors due to crbug.com/746995, not this

Original change's description:
> Revert "android-docker: Wrap container logic in a flock."
> 
> This reverts commit 870016f383048d52d1e8c3f10068416d4d4e6ed8.
> 
> Reason for revert: path/import errors on the bots
> 
> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
> ImportError: No module named site
> 
> Original change's description:
> > android-docker: Wrap container logic in a flock.
> > 
> > R=​jbudorick@chromium.org
> > Bug: 670879
> > Change-Id: I8d8ec754f09617f42505e99c70ae3422d8ad4abc
> > Reviewed-on: https://chromium-review.googlesource.com/557042
> > Reviewed-by: John Budorick <jbudorick@chromium.org>
> > Commit-Queue: Benjamin Pastene <bpastene@chromium.org>
> 
> TBR=bpastene@chromium.org,jbudorick@chromium.org
> 
> # Not skipping CQ checks because original CL landed > 1 day ago.
> 
> Bug: 670879
> Change-Id: I79b6fe697d1de1ecc71dd4d37adc1e69e746b1b8
> Reviewed-on: https://chromium-review.googlesource.com/580370
> Reviewed-by: Benjamin Pastene <bpastene@chromium.org>
> Commit-Queue: Benjamin Pastene <bpastene@chromium.org>

TBR=bpastene@chromium.org,jbudorick@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 670879
Change-Id: I043561c141132b0e152480398f5129b7e29f4c9c