siso: fetch fails if marshaled proto has unknown fields
proto can be marshaled in different type
e.g. *rpb.Action -> *rpb.Directory,

which cause strange error if it is used for different purpose.
e.g. *rpb.Action for `siso fetch -type dir-extract`

Check marshaled proto has no unknown fields
and fail if it has unknown by default.

e.g.
 % ~/go/bin/siso fetch -project rbe-chrome-untrusted -type dir-extract 59094661def66e5b5477abafc086c2d0ef520b9b266d7b0784de98a9b2b1d96a/354 xxx
extract 59094661def66e5b5477abafc086c2d0ef520b9b266d7b0784de98a9b2b1d96a/354 to xxx

Error: failed to unmarshal 59094661def66e5b5477abafc086c2d0ef520b9b266d7b0784de98a9b2b1d96a/354 as *remoteexecution.Directory: unknown fields in marshaled proto: files:{name:"15fa2fa2100e94935052e07edee47aedfbebf605db1d79ca38391c22a32cf262" 2:1596} directories:{name:"8699dfc2241286ed0818f083cdf8904443e7d456eae55ea697b100b214c67556" 2:243} 6:"\x08x" 10:"\n\x11\n\x08OSFamily\x12\x05Linux\n\x9c\x01\n\x0fcontainer-image\x12\x88\x01docker://gcr.io/chops-public-images-prod/rbe/siso-chromium/linux@sha256:912808c295e578ccde53b0685bcd0d56c15d7a03e819dcce70694bfe3fdab35e\n\x19\n\x14label:action_default\x12\x011"
Change-Id: Idb43720c9938cf9e07fcc1dca1554f160d90f5c7
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4861069
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#59659}