Create patch set 3
Change has been successfully rebased and submitted as 6cc18e2763e180929d70c786b419c1f8e6bcc66c

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: go/src/infra/tools/result_adapter/gtest.go
Insertions: 1, Deletions: 1.

@@ -421,7 +421,7 @@
 		logging.Warningf(ctx, "SummaryBase64 is not valid UTF-8 %q", f.SummaryBase64)
 		return nil
 	}
-	summary := string(summaryBytes)
+	summary := strings.TrimSpace(string(summaryBytes))
 	return &pb.FailureReason{
 		PrimaryErrorMessage: truncateString(trimGoogleTestTrace(summary), maxPrimaryErrorBytes),
 	}
```
```
The name of the file: go/src/infra/tools/result_adapter/gtest_test.go
Insertions: 15, Deletions: 2.

@@ -374,6 +374,19 @@
 				})
 				So(tr.FailureReason.PrimaryErrorMessage, ShouldEqual, "error message\n")
 			})
+			Convey("Leading and trailing spaces are removed from failure reason", func() {
+				input := "  error\n message\n  "
+				tr := convert(&GTestRunResult{
+					Status: "FAILURE",
+					ResultParts: []*GTestRunResultPart{
+						{
+							SummaryBase64: base64.StdEncoding.EncodeToString([]byte(input)),
+							Type:          "failure",
+						},
+					},
+				})
+				So(tr.FailureReason.PrimaryErrorMessage, ShouldEqual, "error\n message")
+			})
 			Convey("empty", func() {
 				tr := convert(&GTestRunResult{
 					Status:      "FAILURE",
@@ -505,7 +518,7 @@
 		Convey("GTest Expectation", func() {
 			// Test a log with multiple expectation failures, to make
 			// sure only one gets picekd up.
-			example := `One log line
+			example := `Unrelated log line
 ../../content/public/test/browser_test_base.cc:718: Failure
 Expected equality of these values:
   expected_exit_code_
@@ -526,7 +539,7 @@
 			test(example, expected)
 		})
 		Convey("GTest Expectation (Windows)", func() {
-			example := `One log line
+			example := `Unrelated log line
 ../../chrome/browser/net/network_context_configuration_browsertest.cc(984): error: Expected equality of these values:
   net::ERR_CONNECTION_REFUSED
     Which is: -102
```


Patch-set: 3
Patch-set-description: Rebase
Subject: [Weetbix] Improve failure reason extraction in result adapter.
Status: merged
Commit: 6cc18e2763e180929d70c786b419c1f8e6bcc66c
Tag: autogenerated:gerrit:merged
Groups: acd057847f2ac0f7db500f5b05844e8db51ee5d1
Label: Code-Review=+1, cc7b5d20345ce3e056a2ed4655d5ca1966e2b30e Gerrit User 1157909 <1157909@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, ee8ce40002bcc71a1dba5ec7f6388744a3ae136b Gerrit User 1386944 <1386944@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, 263cab081ecdfc9267593a3055243a96a9325595
Submission-id: 3529908
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1157909 <1157909@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1386944 <1386944@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Auto-Submit
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1419112 \u003c1419112@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"REMOVE","reason":"Change was submitted"}