[go] Remove gopls.
It is not really used by any bot. It was added to tools.go as
a convenience for installing it on dev workstations. I'm not
sure who actually relies on that though (many editors have their
own way to fetch LSP server binaries).

But gopls@latest doesn't work with x/tools@latest causing
complications when updating other modules that want
x/tools@latest.

Compiling gopls@latest + x/tools@latest results in:

```
../../../../.modcache/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/view.go:815:36: undefined: gocommand.GoVersionString
```

If gopls is needed, it can be installed manually using
`go install golang.org/x/tools/gopls@latest`. This uses whatever
old revision gopls was released with instead of @latest in
infra's go.mod.

R=iannucci@chromium.org

Change-Id: I472ab6de4d8b3e194e0a7508039a51a07b1ea170
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4190123
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Cr-Commit-Position: refs/heads/main@{#54133}