shivas: update add machine with json to have one less layer of nesting
Tested locally and checked tests. However:

- Ran `make test` which passed but observed that there were no unit tests for this

- Local tests didn't fully work because of http://yaqs/8120778477986119680 (although I was able to verify that the JSON parsing part of the code before the UFS request succeeded):

Before this change:
```
$ ./shivas add machine -f ~/sample-data/machine.json
add: proto: (line 2:5): unknown field "name"
```

After this change:
```
$ ./shivas add machine -f ~/sample-data/machine.json
add: rpc error: code = PermissionDenied desc = user:zhangtiff@google.com is not a member of [mdb/chrome-labs mdb/chrome-fleet-software-team chromeos-inventory-setup-label-write-access chromeos-inventory-status-label-write-access machine-db-writers]
```

Using this sample data (pulled from example given in `shivas add machine --help` / https://source.chromium.org/h/chromium/infra/infra_superproject/+/main:infra/go/src/infra/cmd/shivas/cmdhelp/description.go;l=736 :

```
{
    "name": "machine-OSLAB-example",
    "location": {
        "zone": "ZONE_ATLANTA",
        "aisle": "1",
        "row": "2",
        "rack": "Rack-42",
        "rackNumber": "42",
        "shelf": "3",
        "position": "5"
    },
    "serialNumber": "XXX",
    "chromeosMachine": {}
}
```

BUG=b:273561490
TEST=`./shivas add machine -f ~/sample-data/machine.json` ; `make test`

Change-Id: Ib74c7c7258c19bcc4f5d3b7b8b3227d5e833277a
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5570185
Reviewed-by: Yang Yang <echoyang@chromium.org>
Commit-Queue: Tiffany Zhang <zhangtiff@chromium.org>
Cr-Commit-Position: refs/heads/main@{#65717}